package pigpio4s;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class rawWaveInfo_t extends Structure {
	/** first CB used by wave */
	public short botCB;
	/** last CB used by wave */
	public short topCB;
	/** first bottom OOL used by wave */
	public short botOOL;
	/**
	 * botOOL to botOOL + numBOOL -1 are in use<br>
	 * last top OOL used by wave
	 */
	public short topOOL;
	/** topOOL - numTOOL to topOOL are in use. */
	public short deleted;
	public short numCB;
	public short numBOOL;
	public short numTOOL;
	public rawWaveInfo_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("botCB", "topCB", "botOOL", "topOOL", "deleted", "numCB", "numBOOL", "numTOOL");
	}
	public rawWaveInfo_t(short botCB, short topCB, short botOOL, short topOOL, short deleted, short numCB, short numBOOL, short numTOOL) {
		super();
		this.botCB = botCB;
		this.topCB = topCB;
		this.botOOL = botOOL;
		this.topOOL = topOOL;
		this.deleted = deleted;
		this.numCB = numCB;
		this.numBOOL = numBOOL;
		this.numTOOL = numTOOL;
	}
	public rawWaveInfo_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends rawWaveInfo_t implements Structure.ByReference {
		
	};
	public static class ByValue extends rawWaveInfo_t implements Structure.ByValue {
		
	};
}
