package rxgpio;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class gpioReport_t extends Structure {
	public short seqno;
	public short flags;
	public int tick;
	public int level;
	public gpioReport_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("seqno", "flags", "tick", "level");
	}
	public gpioReport_t(short seqno, short flags, int tick, int level) {
		super();
		this.seqno = seqno;
		this.flags = flags;
		this.tick = tick;
		this.level = level;
	}
	public gpioReport_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends gpioReport_t implements Structure.ByReference {
		
	};
	public static class ByValue extends gpioReport_t implements Structure.ByValue {
		
	};
}
