package rxgpio;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class gpioHeader_t extends Structure {
	public short func;
	public short size;
	public gpioHeader_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("func", "size");
	}
	public gpioHeader_t(short func, short size) {
		super();
		this.func = func;
		this.size = size;
	}
	public gpioHeader_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends gpioHeader_t implements Structure.ByReference {
		
	};
	public static class ByValue extends gpioHeader_t implements Structure.ByValue {
		
	};
}
